### PR TITLE
Improve glsl shader performance

### PR DESCRIPTION
**Pull request by uis246**
Most optimizations are done by abusing mathematical properties and replacing slow on some hardware(e.g. Inetl) min and max with saturation.
For example dot product is in range [-1, 1], so `max(0, dot(...))` = `sat(dot(...))`.
In places where this potentially can mess with HDR comments were added.

### CODE REVIEW

**Comment by uis246** [comment]
Riiight, forgot to rebase.

**Review by hemebond — APPROVED** [review]

**Comment by hemebond** [comment]
> Seems good; someone else please test run this before merging though.

I've tested it with Quake. I didn't notice any problems. @uis246 if there's any in particular that might be affected please let me know.

**Comment by uis246** [comment]
I've used only properties of linear algebra(like elements of normalized vector are always in range of [-1, 1]), basic arithmetics, shuffling between registers, using proper built-ins instead of hacks and assumption of samples being in range of [0, 1]. Seems to be it.

**Comment by uis246** [comment]
So there should be no existing game being affected

**Review by divVerent — APPROVED** [review]
Looked through it once more - if it's not _horribly_ breaking as is, it's good to merge.

**Pull request merged**
