### PR TITLE
Added Webassembly support and fixed GLES2 errors

### PR DESCRIPTION
**Pull request by Lockl00p**
It's as the title said. Whoever screwed up GLES2 needs to take a long walk off a short pier.

### CODE REVIEW

**Comment by bones-was-here** [comment]
Precompiled libs are a huge maintenance headache that took a lot of time to get past for Xonotic builds, please don't reintroduce them...

**Comment by Lockl00p** [comment]
I only attached buildscripts for required libraries.

**Comment by bones-was-here** [comment]
libs

**Comment by Lockl00p** [comment]
Ohhhh d0blindid. I might have to fix that

**Comment by Lockl00p** [comment]
> libs

Fixed

**Pull request closed without merging**
