### PR TITLE
Fix a bug on FreeBSD caused by assuming that short reads are errors

### PR DESCRIPTION
**Pull request by notcancername**

### CODE REVIEW

**Review by bones-was-here — CHANGES_REQUESTED** [review]
Hi, thanks for looking at this, seems like this assumption shouldn't be made on other platforms too, from linux `read(2)` manpage: "It  is  not an error if this number is smaller than the number of bytes requested" and we'd need this logic to read files bigger than 2GiB.

In the case where `USE_RWOPS` is defined (currently that looks to be android only, which nobody tests :upside_down_face:) SDL's `SDL_RWread()` is used, which I believe doesn't need to be wrapped like this.  
So I'd prefer if you would change the `# define FILEDESC_READ read` line to your func and then call `read` from there directly, it should be cleaner than redefining.  Same for `write`.

Also please use the [CONTRIBUTING.md](https://github.com/DarkPlacesEngine/darkplaces/blob/master/CONTRIBUTING.md) code style, and signoff your commit(s) - `git commit --amend -s` should be sufficient.

**Comment by notcancername** [comment]
According to [the SDL docs](<https://wiki.libsdl.org/SDL2/SDL_RWread>), short reads are possible. Redefining `FILEDESC_READ` and `FILEDESC_WRITE` seems like the more general solution here. I'll apply the preferred code style and sign off the commit.

> we'd need this logic to read files bigger than 2GiB.

I don't understand what's meant by this, could you explain?

**Comment by bones-was-here** [comment]
> According to [the SDL docs](https://wiki.libsdl.org/SDL2/SDL_RWread), short reads are possible.

Ah ok no worries.  That would seem to limit the usefulness of the abstraction since developers using SDL still need to be aware of this detail and handle it themselves.

> I don't understand what's meant by this, could you explain?

The manpage for read(2) says: "On  Linux,  read()  (and  similar  system calls) will transfer at most 0x7ffff000 (2,147,479,552) bytes, returning the number of bytes actually transferred.  (This is true on both 32-bit and 64-bit systems.)"  
So if we wanted to read a 3GB file, we would need this logic (looping until the file has been completely read).

---

DP uses tabs for indenting, please :) your editor seems to have created an odd mess.  
No need to split `static fs_offset_t
ReadAll (const filedesc_t fd, void *const buf, const size_t length)` over 2 lines.

**Comment by notcancername** [comment]
> Ah ok no worries. That would seem to limit the usefulness of the abstraction since developers using SDL still need to be aware of this detail and handle it themselves.

Eh, it's useful in some cases. 

> DP uses tabs for indenting, please :) your editor seems to have created an odd mess.

I just used `indent -bsd` on these functions Allman style. Will make it use tabs.

**Review by bones-was-here — APPROVED** [review]
I see you gave me push access to the branch so I amended the style to be more DPish.

**Pull request merged**
