### PR TITLE
Added Webassembly support and fixed GLES2 (somewhat)

### PR DESCRIPTION
**Pull request by Lockl00p**
Webassembly version doesn’t work online and screen flashes on GLES2 are opaque.

### CODE REVIEW

**Comment by Cloudwalk9** [comment]
This is going to be merged one way or another eventually but we're moving at below glacial pace due to the nature of volunteer work and the complexity of implementing support for a new platform. General reminder not to feel discouraged.

**Review by bones-was-here — CHANGES_REQUESTED** [review]
Could you fix all the compiler warnings in sys_wasm.c please? New code shouldn't have any warns.  
Don't worry about the warns in other files, they're not caused by your code and are harmless (mostly unused variables due to compiling GLES, we can clean up GLES in another PR).

**Comment by bones-was-here** [comment]
I have a bit more tidying and testing todo but then I think it'll be good to merge, planning to do that Sunday (unless someone finds an issue)

**Review by bones-was-here — APPROVED** [review]

**Comment by Cloudwalk9** [comment]
Great work guys.

**Pull request merged**
